### ISSUE TITLE
EntisGLS tools

### ISSUE THREAD

**Issue by baffy-rr** [Dir-A/NekoPackTools#1]
Sorry to write here, but I can't find the EntisGLS utility in your repositories.

Example, here you have an unpacked script.csx
https://github.com/Dir-A/GalTextAll_CN/tree/main/Text_Extract/Ouchi%20ni%20Kaeru%20made/Script_JP

**Comment by Dir-A** [comment]
You might want to take a look at this https://github.com/jszhtian/EntisGLS-Engine

I do not quite understand what you mean

csx files can be extracted by garbro
you just need to keep the directory structure in the game directory to be read by the game without repack

csx files do contain text in older versions, but text is sorted, like A-Z, Z-A, etc.
text encoding is UTF16-LE you can pull csx file directly into hex editor to see.

text of the new version of EntisGLS is placed in xml file independently of csx
this means that you can edit xml file to modify the text, and then just put the files directly into game directory keeping the directory structure.

If you need to edit an older version of the text, take a look at the project I mentioned at beginning

But things don't always go smoothly, some EntisGLS scripts have been modified, so existing tools may not always work directly

**Comment by Cosetto** [comment]
> Sorry to write here, but I can't find the EntisGLS utility in your repositories.
> 
> Example, here you have an unpacked script.csx https://github.com/Dir-A/GalTextAll_CN/tree/main/Text_Extract/Ouchi%20ni%20Kaeru%20made/Script_JP

For scrxml, use [this](https://github.com/regomne/chinesize/blob/master/entis_gls/extAndChi/exTxtFromXml.py)
